In [40]:
import numpy as np
import pandas as pd
import math
from itertools import product, chain
import re

In [107]:
# data = np.loadtxt('Day10_input_test.txt')
data = np.loadtxt('Day10_input.txt')
data[-5:]

array([ 73.,  74.,  87., 182.,  35.])

In [108]:
dev_jolt = np.max(data) + 3
data = np.append(data, [0, dev_jolt])

# Part 1

In [109]:
ordered = np.sort(data)
diffs = np.diff(ordered)
ones = np.sum(diffs == 1)
threes = np.sum(diffs == 3)
print(ones, threes, ones*threes)

74 37 2738


# Part 2

In [110]:
ordered

array([  0.,   1.,   2.,   5.,   6.,   7.,   8.,   9.,  12.,  13.,  16.,
        17.,  18.,  19.,  22.,  25.,  26.,  27.,  28.,  31.,  34.,  35.,
        36.,  37.,  38.,  41.,  44.,  45.,  46.,  47.,  48.,  51.,  52.,
        53.,  56.,  59.,  60.,  61.,  62.,  65.,  66.,  67.,  68.,  71.,
        72.,  73.,  74.,  75.,  78.,  81.,  84.,  87.,  88.,  89.,  90.,
        93.,  94.,  95.,  98.,  99., 102., 103., 104., 105., 106., 109.,
       110., 111., 112., 113., 116., 117., 118., 121., 122., 123., 124.,
       127., 130., 133., 134., 135., 136., 137., 140., 141., 142., 145.,
       146., 147., 148., 149., 152., 153., 156., 159., 160., 161., 164.,
       165., 168., 169., 170., 171., 172., 175., 178., 179., 180., 181.,
       182., 185.])

In [111]:
diffs

array([1., 1., 3., 1., 1., 1., 1., 3., 1., 3., 1., 1., 1., 3., 3., 1., 1.,
       1., 3., 3., 1., 1., 1., 1., 3., 3., 1., 1., 1., 1., 3., 1., 1., 3.,
       3., 1., 1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 1., 3., 3., 3., 3.,
       1., 1., 1., 3., 1., 1., 3., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 3., 1., 1., 3., 1., 1., 1., 3., 3., 3., 1., 1., 1., 1., 3., 1.,
       1., 3., 1., 1., 1., 1., 3., 1., 3., 3., 1., 1., 3., 1., 3., 1., 1.,
       1., 1., 3., 3., 1., 1., 1., 1., 3.])

In [112]:
three_ids = np.where(diffs == 3)[0]
three_ids

array([  2,   7,   9,  13,  14,  18,  19,  24,  25,  30,  33,  34,  38,
        42,  47,  48,  49,  50,  54,  57,  59,  64,  69,  72,  76,  77,
        78,  83,  86,  91,  93,  94,  97,  99, 104, 105, 110], dtype=int64)

In [113]:
chunks = np.diff(three_ids, prepend=-1, append=max(three_ids+1))
chunks

array([3, 5, 2, 4, 1, 4, 1, 5, 1, 5, 3, 1, 4, 4, 5, 1, 1, 1, 4, 3, 2, 5,
       5, 3, 4, 1, 1, 5, 3, 5, 2, 1, 3, 2, 5, 1, 5, 1], dtype=int64)

In [114]:
def combs(num):
    if num <= 2:
        return 1
    elif num == 3:
        return 2
    elif num == 4:
        return 4
    elif num == 5:
        return 7
    else:
        raise NotImplementedError
    
    

In [118]:
combinations = list(map(combs, chunks))
combinations

[2,
 7,
 1,
 4,
 1,
 4,
 1,
 7,
 1,
 7,
 2,
 1,
 4,
 4,
 7,
 1,
 1,
 1,
 4,
 2,
 1,
 7,
 7,
 2,
 4,
 1,
 1,
 7,
 2,
 7,
 1,
 1,
 2,
 1,
 7,
 1,
 7,
 1]

In [120]:
int(np.product(combinations, dtype=np.float64))

74049191673856